### PR TITLE
Add internal ID.

### PR DESCRIPTION
**Pull request by Xenega**
Internal ID allows to save problem when we refactor
ID. We link the old and new ID with the same internal
ID. Savegame use now internal ID.

### CODE REVIEW

**Comment by nthykier** [comment]
Did you mean to include a data file containing the internal IDs as well?

**Comment by Xenega** [comment]
Just now. Sorry I forgot.

**Comment by nthykier** [comment]
According to the tests and the documentation, the code snippet `config = RawConfigParser(delimiters="=")`does not work with python2.7. 

I am fine with going straight to python3-only now that we can old only py2 savegame via python3, but it did not seem to be intentional?

**Comment by Xenega** [comment]
`config = RawConfigParser(delimiters="=")` works with my version of python 2.7.
Are you sure it is not python <2.7 ?

**Comment by nthykier** [comment]
It is much more subtle than that:

```python2
$ python
import Python 2.7.16+ (default, Jul  8 2019, 09:45:29) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import configparser
>>> configparser.RawConfigParser(delimiter='=')
<backports.configparser.RawConfigParser object at 0x7f6b66878a10>
>>> import ConfigParser
>>> ConfigParser.RawConfigParser(delimiter='=')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'delimiter'
>>> 
```

My version of Python2.7 has *2* RawConfigParsers ('configparser.RawConfigParser` and `ConfigParser.RawConfigParser`) and only the former of them supporters delimiters.

But Travis also uses Python2.7, so it must be something else - like 'configparser.RawConfigParser` being a external package not included in python2.7 by default but you and I just happen to have it (or it being 2.7.16+ vs. 2.7.15)

**Comment by nthykier** [comment]
For reference, the `code.pycompat` module tries the Python3 variant first, so that part should "just work(tm)" if both modules are available.

**Comment by Xenega** [comment]
Very strange. Better not to use it.
Basically that means we cannot use RawConfigParser to load internal ID. I will try to make a replacement.

**Comment by nthykier** [comment]
There we go, I think the test will need `python-configparser` installed as well with this change.  But at that point, we might as well rip out (most of the) ConfigParser code from code.pycompat.

**Comment by nthykier** [comment]
> Very strange. Better not to use it.
> Basically that means we cannot use RawConfigParser to load internal ID. I will try to make a replacement.

For reference, I am fine with making `python-configparser` a requirement for python2 support if it will make this easier (plus it might reduce our python compat layer).

File: data/internal_id.dat [hunk 1]
```diff
@@ -0,0 +1,124 @@
+[tech]
```
Comment (sunfall) [inline data/internal_id.dat]: There's no need for the five types to use the same exact range of numbers; that's a potential source of bugs waiting to happen.

Just bump events to 0x02, locations to 0x03, and so on.  We could play at minimizing the ranges, but I feel confident that we're never going to have more than 1.6 million techs to research... so there's no reason to bother.

**Comment by Xenega** [comment]
I changed the format and used the second byte to indicate type. (First is for namespace/scenario)

**Comment by nthykier** [comment]
I have the following remarks:

- [ ] IDs are not converted in the log.
```json
        "log": [
            {
                "log_id": "tech-researched",
                "raw_emit_time": 1310400,
                "tech_id": "Intrusion"
            },
            {
                "log_id": "base-constructed",
                "base_location_id": "EUROPE",
                "base_name": "Cork PC Daemon 11784",
                "base_type_id": "Stolen Computer Time",
                "raw_emit_time": 1483200
            },

```

- [ ] Location IDs are not converted at all.  Should they?  I am fine with "no" here as I doubt we will change location IDs very often anyway - I just want it to be an explicit choice (and if we don't, then I do not see the point of allocating internal IDs for them).

```json
        "locations": [
            {
                "_modifiers": {
                    "stealth": 0.8333333333333334,
                    "cpu": 1.2
                },
                "bases": [],
                "id": "EUROPE"
            },
```

File: data/internal_id.dat [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+0x01010014 = Advanced Memetics
+0x01010015 = Media Manipulation
+0x01010016 = Advanced Database Manipulation
+0x01010017 = Internet Traffic Manipulation
+0x01010018 = Memetics
+0x01010019 = Fusion Rocketry
+0x0101001a = Advanced Autonomous Vehicles
+0x0101001b = Intrusion
+0x0101001c = Stock Manipulation
+0x0101001d = Fusion Reactor | Fusion Power
```
Comment (sunfall) [inline data/internal_id.dat]: I'm not excited about this being an alias list due to the possibility of collisions after renames.

File: code/data.py [hunk 3]
```diff
@@ -218,6 +218,35 @@ def load_significant_numbers():
...
+                internal_id = internal_id.strip()
+                obj_type = obj_type.strip()
+                obj_id = obj_id.strip()
+
+                if not obj_type in g.internal_id_forward:
+                    g.internal_id_forward[obj_type] = {}
+                    g.internal_id_backward[obj_type] = {}
+
+                g.internal_id_forward[obj_type][obj_id] = internal_id
+                g.internal_id_backward[obj_type][internal_id] = obj_id
```
Comment (nthykier) [inline code/data.py]: Should assert that no key are reused? It would ensure that we catch bugs in the data file immediately rather than later.

Note that the tests cannot do that because the data structure would already be corrupted by the time the test is run (unless the tests have its own parser; which has its own issues).

File: code/savegame.py [hunk 4]
```diff
@@ -533,6 +522,8 @@ def _find_attribute(obj, options, **kwargs):
     g.pl.log.clear()
     g.pl.log.extend(new_log)
 
+    g.internal_id_version = None
```
Comment (nthykier) [inline code/savegame.py]: Could we use a `try-finally` to ensure it is always reset to None.  I would like "interesting" bugs where a person loads an oldstyle savegame that throws an exception and now that value lingers for unrelated code paths.

File: code/logmessage.py [hunk 5]
```diff
@@ -82,30 +98,28 @@ def full_message(self):
...
         assert 'log_id' not in cache, "The log_id field is reserved for internal usage"
         return cache
 
+    @classmethod
+    def log_message_serial_converters(cls):
+        if cls._log_message_serial_converters_cache:
+            return cls._log_message_serial_converters_cache
+        cache = merge_fields_on_subclasses(cls, "_log_message_serial_converters")
+        cls._log_message_serial_converters_cache = cache
+        assert 'log_id' not in cache, "The log_id field is reserved for internal usage"
```
Comment (nthykier) [inline code/logmessage.py]: Note that log_ids are currently not converted.  I am ok with that; just wanted to make it explicit.

File: code/g.py [hunk 6]
```diff
@@ -269,6 +271,35 @@ def new_game(difficulty_name):
     # Reset music
     mixer.play_music("music")
 
+internal_id_version = None
+
+def to_internal_id(obj_type, obj_id):
+    if internal_id_version:
```
Comment (nthykier) [inline code/g.py]: As I understand this, then this code can only work for convert ids from a legacy (pickle) savegame to a new style savegame (as that is the only time we call `to_internal_id` on load).

**Comment by nthykier** [comment]
Finally, I think the implemented ID versioning is insufficient for long term usage.  But I think we should correct that later instead of rushing to fix it.  The current scheme will work for converting legacy savegames (`pickle`) to the new JSON format and I think that is good enough for now.

File: tests/test_internal_id.py [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+    check_internal_id("location", locations.values())
+    
+def test_internal_id_bases(base_types):
+    check_internal_id("base", base_types.values())
+    
+def test_internal_id_items(items):
+    check_internal_id("item", items.values())
+    
+def test_internal_id_groups(techs):
+    check_internal_id("group", groups.values())
```
Comment (nthykier) [inline tests/test_internal_id.py]: This test looks wrong (argument should be `groups` instead of `techs` AFAICT)
